name: Run Ansible Lab

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible --version

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Criar inventory dinamicamente
        run: |
          cat > inventory <<EOF
          [server]
          ${{ vars.SERVER_IP }} ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519
          EOF

          echo "===== INVENTORY ====="
          cat inventory

      - name: Testar conectividade com Ansible
        run: |
          ansible -i inventory server -m ping

      - name: Executar playbook
        run: |
          ansible-playbook -i inventory ansible/playbook.yml
