name: Test GitHub Actions
on:
  workflow_dispatch:

jobs:

  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible --version
