name: Test GitHub Actions
on:
  workflow_dispatch:

jobs:

  teste:

    runs-on: ubuntu-latest

    steps:

      - name: Mostrar sistema
        run: |
          echo "GitHub Actions funcionando"
          whoami
          pwd
          uname -a
